### ISSUE TITLE
Code for calculating flops

### ISSUE THREAD

**Issue by siqiZ805** [CrystalSixone/VLN-MAGIC#1]
Thank you for your exceptional work! However, I'm curious about the method you use to calculate FLOPs. I attempted to follow the approach mentioned in your paper, specifically using a batch size of 8, instruction length of 44, candidates node of 3, and visited nodes of 6. Unfortunately, I couldn't obtain the same results as yours. Would it be possible for you to kindly share the code? Thank you regardless.

**Comment by CrystalSixone** [comment]
Hi! For now, I suggest you infer this [code](https://github.com/CrystalSixone/VLN-GOAT/blob/master/map_nav_src/utils/efficiency_count.py) from GOAT. The code for releasing is being built, and I will release the whole code as soon as possible. Thank you for your attention to our work!
